"""alerta status y umbral/activo en sensores

Revision ID: dc6070b7e00e
Revises: e33cc85ce971
Create Date: 2026-08-21 21:13:39.946538

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc6070b7e00e"
down_revision: str | Sequence[str] | None = "e33cc85ce971"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sensor_id", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("threshold", sa.Float(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sensor_id"],
            ["sensors.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_alerts_sensor_id"), ["sensor_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_status"), ["status"], unique=False
        )

    with op.batch_alter_table("sensors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("alert_threshold", sa.Float(), nullable=True))
        # server_default cubre las filas ya existentes; se retira despues de
        # poblarlas para que el modelo Python siga controlando el default.
        batch_op.add_column(
            sa.Column(
                "active",
                sa.Boolean(),
                nullable=False,
                server_default=sa.true(),
            )
        )
    with op.batch_alter_table("sensors", schema=None) as batch_op:
        batch_op.alter_column("active", server_default=None)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sensors", schema=None) as batch_op:
        batch_op.drop_column("active")
        batch_op.drop_column("alert_threshold")

    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_status"))
        batch_op.drop_index(batch_op.f("ix_alerts_sensor_id"))

    op.drop_table("alerts")
    # ### end Alembic commands ###
